version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      
"80:80"
  environment:
    WORDPRESS_DB_HOST: database-1-docker.cfmuwmyegdds.us-east-1.rds.amazonaws.com
    WORDPRESS_DB_USER: admin
    WORDPRESS_DB_PASSWORD: adminadmin
    WORDPRESS_DB_NAME: banco_de_dados_docker
  volumes:
/efs/wordpress